BookingManager/Controllers/catogoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BookingManager.Models;

namespace BookingManager.Controllers
{
    public class catogoriesController : Controller
    {
        private booksEntities2 db = new booksEntities2();

        // GET: catogories
        public ActionResult Index()
        {
            var catogories = db.catogories.Include(c => c.sub_catrogoris);
            return View(catogories.ToList());
        }

        // GET: catogories/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            catogory catogory = db.catogories.Find(id);
            if (catogory == null)
            {
                return HttpNotFound();
            }
            return View(catogory);
        }

        // GET: catogories/Create
        public ActionResult Create()
        {
            ViewBag.catogory_id = new SelectList(db.sub_catrogoris, "subCatogory_id", "name");
            return View();
        }

        // POST: catogories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "catogory_id,name")] catogory catogory)
        {
            if (ModelState.IsValid)
            {
                db.catogories.Add(catogory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.catogory_id = new SelectList(db.sub_catrogoris, "subCatogory_id", "name", catogory.catogory_id);
            return View(catogory);
        }

        // GET: catogories/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            catogory catogory = db.catogories.Find(id);
            if (catogory == null)
            {
                return HttpNotFound();
            }
            ViewBag.catogory_id = new SelectList(db.sub_catrogoris, "subCatogory_id", "name", catogory.catogory_id);
            return View(catogory);
        }

        // POST: catogories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "catogory_id,name")] catogory catogory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(catogory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.catogory_id = new SelectList(db.sub_catrogoris, "subCatogory_id", "name", catogory.catogory_id);
            return View(catogory);
        }

        // GET: catogories/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            catogory catogory = db.catogories.Find(id);
            if (catogory == null)
            {
                return HttpNotFound();
            }
            return View(catogory);
        }

        // POST: catogories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            catogory catogory = db.catogories.Find(id);
            db.catogories.Remove(catogory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BookingManager/Controllers/subcatrogorisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BookingManager.Models;

namespace BookingManager.Controllers
{
    public class subcatrogorisController : Controller
    {
        private booksEntities2 db = new booksEntities2();

        // GET: subcatrogoris
        public ActionResult Index()
        {
            var sub_catrogoris = db.sub_catrogoris.Include(s => s.catogory);
            return View(sub_catrogoris.ToList());
        }

        // GET: subcatrogoris/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            sub_catrogoris sub_catrogoris = db.sub_catrogoris.Find(id);
            if (sub_catrogoris == null)
            {
                return HttpNotFound();
            }
            return View(sub_catrogoris);
        }

        // GET: subcatrogoris/Create
        public ActionResult Create()
        {
            ViewBag.subCatogory_id = new SelectList(db.catogories, "catogory_id", "name");
            return View();
        }

        // POST: subcatrogoris/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "subCatogory_id,name,main_category")] sub_catrogoris sub_catrogoris)
        {
            if (ModelState.IsValid)
            {
                db.sub_catrogoris.Add(sub_catrogoris);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.subCatogory_id = new SelectList(db.catogories, "catogory_id", "name", sub_catrogoris.subCatogory_id);
            return View(sub_catrogoris);
        }

        // GET: subcatrogoris/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            sub_catrogoris sub_catrogoris = db.sub_catrogoris.Find(id);
            if (sub_catrogoris == null)
            {
                return HttpNotFound();
            }
            ViewBag.subCatogory_id = new SelectList(db.catogories, "catogory_id", "name", sub_catrogoris.subCatogory_id);
            return View(sub_catrogoris);
        }

        // POST: subcatrogoris/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "subCatogory_id,name,main_category")] sub_catrogoris sub_catrogoris)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sub_catrogoris).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.subCatogory_id = new SelectList(db.catogories, "catogory_id", "name", sub_catrogoris.subCatogory_id);
            return View(sub_catrogoris);
        }

        // GET: subcatrogoris/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            sub_catrogoris sub_catrogoris = db.sub_catrogoris.Find(id);
            if (sub_catrogoris == null)
            {
                return HttpNotFound();
            }
            return View(sub_catrogoris);
        }

        // POST: subcatrogoris/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            sub_catrogoris sub_catrogoris = db.sub_catrogoris.Find(id);
            db.sub_catrogoris.Remove(sub_catrogoris);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BookingManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Books manager", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("books", "Index", "books")</li>
                    <li>@Html.ActionLink("Catogories", "index", "catogories")</li>
                    <li>@Html.ActionLink("sub catogories", "index", "subcatrogoris")</li>
                    <li>@Html.ActionLink("stackoverflow", "stackoverflow", "books")</li>
                    <li><a href="https://localhost:44355/api/books/">api</a></li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script>
        $(document).ready(function () {
            $("#catogory_id").change(function () {
                
                 $.ajax({url: "/books/GetsubCatrogorisByMain/"+$('#catogory_id').val(), success: function(result){
                     console.log(result);
                    // $("#subcatogory_id").html = "<p>ddd</p>";
                     html = "";
                     result.forEach(element => html+="<option value=\""+element.subCatogory_id+"\">"+element.name+"</option>");

                     document.getElementById("subcatogory_id").innerHTML = html;

                }});
            });
        });

          run();

    function run() {

     $.ajax({url: "https://api.stackexchange.com/2.2/questions?order=desc&sort=activity&tagged=ipv4&site=stackoverflow&filter=!5-dn)8xu6QZI)ZZw.Qkh3LnsZb7HOcBh(7WtBX", success: function(result){
                     console.log(result["items"]);
                    // $("#subcatogory_id").html = "<p>ddd</p>";
                     html = "";
                     result["items"].forEach(element => html += "<li>" + element.title + "</li>");
                     document.getElementById("data").innerHTML = html;

     }
     });
    }


    </script>
</body>
</html>